#tap
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "caskroom/fonts"

# 중요! 이 줄이 없으면, ~/Applications에 설치하므로 꼭 넣어야 한다.
cask_args appdir: '/Applications'

#Binaries/Libraries
brew 'zsh'
brew 'zsh-completions'
brew 'wget'
brew 'tmux'
brew 'git'
brew 'mackup'
brew 'neovim'
brew 'fzf'


# Applications
cask 'homebrew/cask-drivers/logitech-options'
cask 'iterm2'
cask 'google-chrome'
cask 'visual-studio-code'
cask 'android-studio'
cask 'karabiner-elements'
cask 'homebrew/cask-versions/parallels13'


untap 'caskroom/fonts'
tap 'homebrew/cask-fonts'
cask 'font-hack-nerd-font'

