#tap
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "AdoptOpenJDK/openjdk"

# 중요! 이 줄이 없으면, ~/Applications에 설치하므로 꼭 넣어야 한다.
cask_args appdir: '/Applications'

#Binaries/Libraries
brew 'zsh'
brew 'zsh-completions'
brew 'wget'
brew 'tmux'
brew 'git'
brew 'mackup'
brew 'neovim'
brew 'fzf'
brew 'yarn'
brew 'jenkins'
brew 'rbenv'

# Applications
cask 'font-hack-nerd-font'
cask 'homebrew/cask-drivers/logitech-options'
cask 'iterm2'
cask 'font-hack-nerd-font'
cask 'google-chrome'
cask 'visual-studio-code'
cask 'android-studio'
cask 'karabiner-elements'
cask 'keyboard-maestro'
cask 'virtualbox'
cask 'vagrant'
cask 'vagrant-manager'
cask 'postman'
cask 'adoptopenjdk8'
cask 'istat'
cask 'cursorsense'
cask 'istat-menus'
cask 'gitkraken'
cask 'imazing'

